### ISSUE TITLE
Can you create a script to test individual videos?

### ISSUE THREAD

**Issue by tongbc** [facebookresearch/EgoVLPv2#12]

**Comment by ShramanPramanick** [comment]
Thank you for your interest. Would you please explain for which task you want to evaluate an individual video? I can help accordingly.

**Comment by tongbc** [comment]
> Thank you for your interest. Would you please explain for which task you want to evaluate an individual video? I can help accordingly.
Thanks for replying, what I mean is to input a video and a question, input the model to get a response.

**Comment by tongbc** [comment]
> Thank you for your interest. Would you please explain for which task you want to evaluate an individual video? I can help accordingly.

Thanks for replying, what I mean is to input a video and a question, input the model to get a response.
