### ISSUE TITLE
I can't download the pth file. Could you give me a new download link?

### ISSUE THREAD

**Issue by junsang7777** [facebookresearch/EgoVLPv2#20]
I want to use the checkpoint of "Pre-trained checkpoints and results on EgoMCQ" in the "https://github.com/facebookresearch/EgoVLPv2/tree/main/EgoVLPv2 " link. But the download link doesn't seem to work properly. Could you check it please?

**Comment by ShramanPramanick** [comment]
Hi, I just checked that `wget http://www.cis.jhu.edu/~shraman/EgoVLPv2/ckpts/Pre-trained/EgoVLPv2.pth` is working properly. Could you tell me what error you are facing? Maybe it is a network issue? Please try again, and if you still face problems, I can upload it to GDrive and share with you. Thanks.

**Comment by junsang7777** [comment]
I didn't realize if I should use the wget command. Thank you for your quick reply.
